#!/usr/bin/env python
import os
import sys
import argparse

parser = argparse.ArgumentParser()
parser.add_argument("location", default="secret_key", 
                    help="Path to the location where the secret key will be "
                         "stored. The default is a file named \"secret_key\" "
                         "in the current directory",
                    nargs="?")
args = parser.parse_args()
if os.path.exists(args.location):
    sys.stderr.write("ERROR: location \"{0}\" already exists.".format(args.location))
    os.exit(1)

# 512 bits of entropy
SECRET_BYTES = (512 / 8)

with open(args.location, "w") as f:
    f.write(os.urandom(SECRET_BYTES))
